openapi: 3.1.0
info:
  title: Gene MCP Drug for Disease Translator API
  description: |
    This API retrieves drugs associated with a given disease using the Model Context Protocol (MCP).  
    Example query: Find drugs associated with "drug-induced liver injury".
  version: "1.0.0"
  contact:
    name: Broad Institute Translator Team
    url: https://translator.broadinstitute.org

servers:
  - url: https://translator.broadinstitute.org/genetics_provider/gene_mcp

paths:
  /get_drug_for_disease:
    get:
      operationId: getDrugForDisease
      summary: Retrieve drugs associated with a given disease
      description: |
        Returns a list of drug compounds (subjects) that are associated with a specified disease (object).
        The relationships between drugs and diseases are annotated using Biolink model terms.
      parameters:
        - name: input
          in: query
          description: |
            The disease name or condition for which to find associated drug treatments.  
            Example: "drug-induced liver injury".
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response with drug-disease associations.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    description: List of drug-disease association records.
                    items:
                      type: object
                      properties:
                        subject:
                          type: object
                          description: Information about the drug compound associated with the disease.
                          properties:
                            id:
                              type: string
                              description: |
                                Compact identifier (CURIE) for the drug entity.  
                                Typically a CHEBI identifier.
                              example: CHEBI:27560
                            name:
                              type: string
                              description: Common name of the drug compound.
                              example: boron
                        object:
                          type: object
                          description: Information about the disease or phenotype being treated.
                          properties:
                            id:
                              type: string
                              description: |
                                Compact identifier (CURIE) for the disease entity.  
                                Typically a MONDO ontology identifier.
                              example: MONDO:0005359
                            name:
                              type: string
                              description: Human-readable disease or phenotype name.
                              example: drug-induced liver injury
                        relationship:
                          type: string
                          description: |
                            Biolink model relationship describing the connection between the drug and the disease.  
                            Example: "biolink:treats" indicates that the drug treats the disease.
                          example: biolink:treats
                        pubmed_ids:
                          type: array
                          description: |
                            List of supporting PubMed article identifiers (PMIDs) providing evidence for the relationship.
                          items:
                            type: string
                            description: PubMed ID for a scientific publication.
                            example: PMID:30997025
        '400':
          description: Invalid input parameter. Ensure the "input" query parameter is provided and correctly formatted.
        '500':
          description: Internal server error. Indicates a problem with processing the request.
  /get_gene_for_disease:
    get:
      operationId: getGeneForDisease
      summary: Retrieve gene associated with a given disease
      description: |
        Returns a list of genes (subjects) that are associated with a specified disease (object).
        The relationships between genes and diseases are annotated using Biolink model terms.
      parameters:
        - name: input
          in: query
          description: |
            The disease name or condition for which to find associated genes.  
            Example: "drug-induced liver injury".
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response with drug-disease associations.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    description: List of gene-disease association records.
                    items:
                      type: object
                      properties:
                        subject:
                          type: object
                          description: Information about the gene associated with the disease.
                          properties:
                            id:
                              type: string
                              description: |
                                Compact identifier (CURIE) for the gene entity.  
                                Typically a NCBIGene identifier.
                              example: NCBIGene:10144
                            name:
                              type: string
                              description: Common name of the gene.
                              example: FAM13A
                        object:
                          type: object
                          description: Information about the disease or phenotype associated.
                          properties:
                            id:
                              type: string
                              description: |
                                Compact identifier (CURIE) for the disease entity.  
                                Typically a MONDO ontology identifier.
                              example: MONDO:0005359
                            name:
                              type: string
                              description: Human-readable disease or phenotype name.
                              example: drug-induced liver injury
                        relationship:
                          type: string
                          description: |
                            Biolink model relationship describing the connection between the gene and the disease.  
                            Example: "biolink:gene_associated_with_condition" indicates that the gene is genetically associated with the disease.
                          example: biolink:gene_associated_with_condition
                        pubmed_ids:
                          type: array
                          description: |
                            List of supporting PubMed article identifiers (PMIDs) providing evidence for the relationship.
                          items:
                            type: string
                            description: PubMed ID for a scientific publication.
                            example: PMID:30997025
                        score:
                          type: number
                          format: float
                          description: |
                            The computed score between 0 and 1 that reflects the strength of association between the gene and disease
                            Example: 0.875909686 indicates that the gene is strongly genetically associated with the disease.
                          example: 0.875909686
        '400':
          description: Invalid input parameter. Ensure the "input" query parameter is provided and correctly formatted.
        '500':
          description: Internal server error. Indicates a problem with processing the request.
  /get_pathway_for_disease:
    get:
      operationId: getPathwayForDisease
      summary: Retrieve biological process pathway associated with a given disease
      description: |
        Returns a list of biological processes (subjects) that are associated with a specified disease (object).
        The relationships between biological processes and diseases are annotated using Biolink model terms.
      parameters:
        - name: input
          in: query
          description: |
            The disease name or condition for which to find associated genes.  
            Example: "drug-induced liver injury".
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response with drug-disease associations.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    description: List of biological process to disease association records.
                    items:
                      type: object
                      properties:
                        subject:
                          type: object
                          description: Information about the biological process associated with the disease.
                          properties:
                            id:
                              type: string
                              description: |
                                Compact identifier (CURIE) for the biological process entity.  
                                Typically a GO identifier.
                              example: GO:0001637
                            name:
                              type: string
                              description: Common name of the biological process.
                              example: Gomf - G Protein Coupled Chemoattractant Receptor Activity
                        object:
                          type: object
                          description: Information about the disease or phenotype associated.
                          properties:
                            id:
                              type: string
                              description: |
                                Compact identifier (CURIE) for the disease entity.  
                                Typically a MONDO ontology identifier.
                              example: MONDO:0005359
                            name:
                              type: string
                              description: Human-readable disease or phenotype name.
                              example: drug-induced liver injury
                        relationship:
                          type: string
                          description: |
                            Biolink model relationship describing the connection between the biological process and the disease.  
                            Example: "biolink:genetic_association" indicates that the biological process is genetically associated with the disease.
                          example: biolink:genetic_association
                        pubmed_ids:
                          type: array
                          description: |
                            List of supporting PubMed article identifiers (PMIDs) providing evidence for the relationship.
                          items:
                            type: string
                            description: PubMed ID for a scientific publication.
                            example: PMID:30997025
                        p-value:
                          type: number
                          format: float
                          description: |
                            A statistical measure computed by the Magma calculation that helps determine the strength of evidence against a null hypothesis
                            Example: 0.0005 indicates that the biological process is strongly genetically associated with the disease.
                          example: 0.875909686
        '400':
          description: Invalid input parameter. Ensure the "input" query parameter is provided and correctly formatted.
        '500':
          description: Internal server error. Indicates a problem with processing the request.
  /get_drug_for_gene:
    get:
      operationId: getDrugForGene
      summary: Retrieve drugs associated with a given gene
      description: |
        Returns a list of drug compounds (subjects) that are associated with a specified gene (object).
        The relationships between drugs and genes are annotated using Biolink model terms.
      parameters:
        - name: input
          in: query
          description: |
            The gene name or condition for which to find associated drug associations.
            Example: "PPARG".
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response with drug-gene associations.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    description: List of drug-gene association records.
                    items:
                      type: object
                      properties:
                        subject:
                          type: object
                          description: Information about the drug compound associated with the gene.
                          properties:
                            id:
                              type: string
                              description: |
                                Compact identifier (CURIE) for the drug entity.  
                                Typically a CHEBI identifier.
                              example: CHEBI:27560
                            name:
                              type: string
                              description: Common name of the drug compound.
                              example: boron
                        object:
                          type: object
                          description: Information about the gene being impacted.
                          properties:
                            id:
                              type: string
                              description: |
                                Compact identifier (CURIE) for the disease entity.  
                                Typically a NCBIGene ontology identifier.
                              example: NCBIGene:5468
                            name:
                              type: string
                              description: Human-readable gene name.
                              example: PPARG
                        relationship:
                          type: string
                          description: |
                            Biolink model relationship describing the connection between the drug and the gene.  
                            Example: "biolink:affects" indicates that the drug affects the disease.
                          example: biolink:affects
                        pubmed_ids:
                          type: array
                          description: |
                            List of supporting PubMed article identifiers (PMIDs) providing evidence for the relationship.
                          items:
                            type: string
                            description: PubMed ID for a scientific publication.
                            example: PMID:30997025
        '400':
          description: Invalid input parameter. Ensure the "input" query parameter is provided and correctly formatted.
        '500':
          description: Internal server error. Indicates a problem with processing the request.

components:
  schemas:
    Subject:
      type: object
      description: Drug compound information (subject of the association).
      properties:
        id:
          type: string
          description: Compact identifier (CHEBI CURIE) for the drug.
        name:
          type: string
          description: Name of the drug compound.
    Object:
      type: object
      description: Disease or phenotype information (object of the association).
      properties:
        id:
          type: string
          description: Compact identifier (MONDO CURIE) for the disease.
        name:
          type: string
          description: Name of the disease or phenotype.
    ResultItem:
      type: object
      description: Record representing one drug-disease association.
      properties:
        subject:
          $ref: '#/components/schemas/Subject'
        object:
          $ref: '#/components/schemas/Object'
        relationship:
          type: string
          description: Biolink relationship between the drug and the disease.
        pubmed_ids:
          type: array
          description: List of PubMed IDs supporting the relationship.
          items:
            type: string
